#!/usr/bin/python


factory_settings['clamav_default_levels'] = {
	"times": (400,600)
	#'warn': "48",
	#'crit': "72",
}

"""
agent output
<<<clamav>>>
cvd 1459774026
"""

def inventory_clamav(checkname, info):
	inventory = []
	for name, age in info:
		inventory.append((name,None))
	return inventory

def check_clamav(item, params, info):
	import time
	now = int(time.mktime(time.localtime()))
        warn_hours = params['times'][0]
        crit_hours = params['times'][1]
        for line in info:
                if line[0] == item:
			age = abs(int(line[1]) - now)
                        if age >= crit_hours * 3600:
                                rc = 2
                                info = "Clamav Database is {0} hours old".format(age/3600)
                        elif age >= warn_hours * 3600:
                                rc = 1
                                info = "Clamav Database is {0} hours old".format(age/3600)
                        else:
                                rc = 0
                                info = "Clamav Database is {0} hours old".format(age/3600)
        return rc, info


# declare the check to Check_MK
check_info["clamav"] = {
    'check_function':            check_clamav,
    'inventory_function':        inventory_clamav,
    'service_description':       'Age of clamav %s',
    'has_perfdata':       False,
    'group' : 'clamav',
    'default_levels_variable':	'clamav_default_levels',
    }

